## Stack LEPP (Linux (E)Nginx PostgreSQL PHP)
## Find-Replace: "lepp"
## docker network create --driver=overlay frontend_network
## docker network create --driver=overlay lepp_network
## docker stack deploy --compose-file=lepp.yml lepp

version: '3.5'

services:
  php-fpm:
    image: vavyskov/php:7.4-fpm-alpine3.11
    container_name: lepp_php-fpm
    environment:
      PROJECT_MODE: dev
      PHP_USER: stacklepp
      SMTP_HOSTNAME: 192.168.99.100
      SMTP_PORT: 1026
      SMTP_FROM: team@example.com
      SMTP_USER: team
      SMTP_PASSWORD: password
    networks:
      - lepp_network
    volumes:
      - html_data:/var/www/html
    deploy:
      replicas: 1

networks:
  lepp_network:
    external: true

volumes:
  html_data:
    #driver_opts:
    #  type: nfs
    #  o: addr=${NFS_HOSTNAME:-nfs.example.com},nolock,soft,rw
    #  device: :${NFS_PATH:-/media/nfs_docker/dev/lepp/volumes/html_data}
