version: '3'

services:
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    deploy:
      placement:
          constraints: [node.role == manager]
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"