version: '3'

services:
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    ports:
      - "5555:80"
    deploy:
      placement:
          constraints: [node.role == manager]
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.example.com`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=letsEncrypt
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.services.whoami.loadbalancer.server.port=80