## Find-Replace: "whoami-2"
## docker stack deploy --compose-file=whoami-2.yml whoami-2

version: '3.5'

services:
  whoami:
    image: containous/whoami:${WHOAMI_VERSION:-v1.5.0}
    container_name: ${COMPOSE_PROJECT_NAME:-whoami-2}_whoami-2
    #hostname: whoami-2.example.com
    ports:
      - target: 80
        published: ${WHOAMI_PORT:-8086}
      - target: 443
        published: ${WHOAMI_PORT_SSL:-445}
    networks:
      - frontend_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME:-whoami-2}_whoami-2.loadbalancer.server.port=80
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-whoami-2}_whoami-2.rule=Host(`whoami-2.example.com`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-whoami-2}_whoami-2.tls=true

networks:
  frontend_network:
    external: true
