version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:${NGINX_PROXY_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME:-nginx-proxy}_nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../mkcert/certificates:/etc/nginx/certs:ro
#    environment:
#      HSTS: "off"
#      HSTS: "max-age=31536000; includeSubDomains; preload"
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    networks:
      - frontend_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  frontend_network:
    external: true