## Stack LEPP (Linux (E)Nginx PostgreSQL PHP)

version: '3.8'

services:
  nginx:
    image: vavyskov/nginx:${NGINX_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    hostname: ${PROJECT_HOSTNAME}
    volumes:
#      - html_data:${PROJECT_ROOT}:nocopy
      - ..:${PROJECT_ROOT}
      ## Custom certificates (set path also in dynamic/certificates.yml)
      - ../../../project-environment/certificates:/etc/ssl/certificates:ro
    depends_on:
      - php-fpm
    environment:
      PROJECT_HOSTNAME: ${PROJECT_HOSTNAME}
      FASTCGI_HOSTNAME: ${COMPOSE_PROJECT_NAME}_php-fpm
      CERTIFICATE_PATH: ${CERTIFICATE_PATH}
      CERTIFICATE_FILENAME: ${CERTIFICATE_FILENAME}
      CERTIFICATE_KEYNAME: ${CERTIFICATE_KEYNAME}
    ports:
      - target: 80
        published: ${NGINX_PORT}
    networks:
      - frontend_network
      - backend_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_nginx.loadbalancer.server.port=80
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_nginx.rule=Host(`${PROJECT_HOSTNAME}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_nginx.tls=true

  php-ssh:
    image: vavyskov/php:${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_php-ssh
    hostname: ${COMPOSE_PROJECT_NAME}_php-ssh
    depends_on:
      - php-fpm
    environment:
      PROJECT_MODE: ${PROJECT_MODE}
      PHP_USER: ${PHP_USER}
      PHP_PASSWORD: ${PHP_PASSWORD}
      GIT_EMAIL: ${GIT_EMAIL}
      GIT_NAME: ${GIT_NAME}
      PHP_SENDMAIL_PATH: ${PHP_SENDMAIL_PATH}
      SMTP_HOSTNAME: ${SMTP_HOSTNAME}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      PROXY_SERVER: ${PROXY_SERVER}
      HOST_USER_ID: ${HOST_USER_ID}
      PHP_INI: |
        memory_limit = -1
        upload_max_filesize = 128M
    command: /usr/sbin/sshd -D
    ports:
      - target: 22
        published: ${SSH_PORT}
    networks:
      - backend_network
      - project_network
    volumes:
#      - html_data:${PROJECT_ROOT}:nocopy
      - ..:${PROJECT_ROOT}
#      - ~/.ssh:${SSH_HOME}/.shared/.ssh
#      - ~/.gitconfig:${SSH_HOME}/.shared/.gitconfig
      - ../../../project-environment/certificates/rootCA.crt:/usr/local/share/ca-certificates/rootCA.crt
    deploy:
      replicas: 1

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      LC_COLLATE: ${LC_COLLATE}
      LC_CTYPE: ${LC_CTYPE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - target: 5432
        published: ${POSTGRES_PORT}
    networks:
      - database_network
      - project_network
    deploy:
      replicas: 1

  php-cron:
    image: vavyskov/php:${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_php-cron
    environment:
      PROJECT_MODE: ${PROJECT_MODE}
      PHP_USER: ${PHP_USER}
      PHP_SENDMAIL_PATH: ${PHP_SENDMAIL_PATH}
      SMTP_HOSTNAME: ${SMTP_HOSTNAME}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      HOST_USER_ID: ${HOST_USER_ID}
      PHP_CRONTAB: |
        * * * * * php -r "mail('test@example.com','CRON mail (LEPP)', 'Test e-mail from CRON.', 'From: cron@example.com');"
        2 * * * * php -r "mail('test@example.com','CRON mail 2 (LEPP)', 'Test 2 e-mail from CRON.', 'From: cron@example.com');"
    command: /usr/sbin/crond -f -d 0
    networks:
      - backend_network
      - project_network
    volumes:
#      - html_data:${PROJECT_ROOT}
      - ..:${PROJECT_ROOT}
      - ../../../project-environment/certificates/rootCA.crt:/usr/local/share/ca-certificates/rootCA.crt
    deploy:
      replicas: 1

networks:
  frontend_network:
    external: true
  backend_network:
    external: true
  database_network:
    external: true
  project_network:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_network

volumes:
#  html_data:
#    name: ${COMPOSE_PROJECT_NAME}_html_data
##    driver_opts:
##      type: nfs
##      o: addr=${NFS_HOSTNAME},nolock,soft,rw
##      device: :${NFS_PATH}/${COMPOSE_PROJECT_NAME}/volumes/html_data
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME}_postgres_data
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_HOSTNAME},nolock,soft,rw
#      device: :${NFS_PATH}/${COMPOSE_PROJECT_NAME}/volumes/postgres_data
