version: '4'

services:
  httpd-proxy:
    image: vavyskov/httpd-proxy:${HTTPD_PROXY_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_httpd-proxy
    volumes:
      - ./config/sites:/usr/local/apache2/conf/sites:ro
#    ports:
#      - target: 80
#        published: 90
    networks:
      - frontend_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_httpd-proxy.loadbalancer.server.port=80
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_httpd-proxy.rule=Host(`${PROJECT_HOSTNAME}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_httpd-proxy.tls=true

networks:
  frontend_network:
    external: true