## Stack LEMP (Linux (E)Nginx MySQL/MariaDB PHP)

version: '3.8'

services:
  nginx:
    image: vavyskov/nginx:${NGINX_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    hostname: ${PROJECT_HOSTNAME}
    volumes:
#      - html_data:${PROJECT_ROOT}:nocopy
      - ../codebase:${PROJECT_ROOT}
    depends_on:
      - php-fpm
    environment:
      PROJECT_HOSTNAME: ${PROJECT_HOSTNAME}
      ## Nginx-proxy
      VIRTUAL_HOST: ${PROJECT_HOSTNAME}
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
    ports:
      - target: 80
        published: ${NGINX_PORT}
    networks:
      - frontend_network
      - project_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_nginx.loadbalancer.server.port=80
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_nginx.rule=Host(`${PROJECT_HOSTNAME}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_nginx.tls=true

  php-ssh:
    image: vavyskov/php:${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_php-ssh
    hostname: ${COMPOSE_PROJECT_NAME}_php-ssh
    depends_on:
      - php-fpm
    environment:
      PROJECT_MODE: ${PROJECT_MODE}
      PHP_USER: ${PHP_USER}
      PHP_PASSWORD: ${PHP_PASSWORD}
      GIT_EMAIL: ${GIT_EMAIL}
      GIT_NAME: ${GIT_NAME}
      PHP_SENDMAIL_PATH: ${PHP_SENDMAIL_PATH}
      SMTP_HOSTNAME: ${SMTP_HOSTNAME}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      PROXY_SERVER: ${PROXY_SERVER}
      HOST_USER_ID: ${HOST_USER_ID}
      PHP_INI: |
        memory_limit = -1
        upload_max_filesize = 128M
    command: /usr/sbin/sshd -D
    ports:
      - target: 22
        published: ${SSH_PORT}
    networks:
      - project_network
    volumes:
#      - html_data:${PROJECT_ROOT}:nocopy
      - ../codebase:${PROJECT_ROOT}
#      - ~/.ssh:${SSH_HOME}/.shared/.ssh
#      - ~/.gitconfig:${SSH_HOME}/.shared/.gitconfig
    deploy:
      replicas: 1

  mariadb:
#    image: mariadb:${MARIADB_VERSION}
    image: wodby/mariadb:${MARIADB_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    environment:
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_czech_ci"]
    volumes:
      #- ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    ports:
      - target: 3306
        published: ${MARIADB_PORT}
    networks:
#      - frontend_network
      - project_network
    deploy:
      replicas: 1

  mailcatcher:
    image: vavyskov/mailcatcher:${MAILCATCHER_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_mailcatcher
    environment:
      ## Nginx-proxy
      VIRTUAL_HOST: mailcatcher-${PROJECT_HOSTNAME}
      VIRTUAL_PORT: 80
    ports:
      - target: 80
        published: ${MAILCATCHER_PORT}
      - target: 25
        published: ${SMTP_PORT}
    networks:
      - frontend_network
      - project_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_mailcatcher.loadbalancer.server.port=80
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_mailcatcher.rule=Host(`mailcatcher-${PROJECT_HOSTNAME}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_mailcatcher.tls=true

  adminer:
    image: adminer:${ADMINER_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    environment:
      ## Nginx-proxy
      VIRTUAL_HOST: adminer-${PROJECT_HOSTNAME}
      VIRTUAL_PORT: 8080
    ports:
      - target: 8080
        published: ${ADMINER_PORT}
    networks:
      - frontend_network
      - project_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_adminer.loadbalancer.server.port=8080
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_adminer.rule=Host(`adminer-${PROJECT_HOSTNAME}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_adminer.tls=true

  php-cron:
    image: vavyskov/php:${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_php-cron
    environment:
      PROJECT_MODE: ${PROJECT_MODE}
      PHP_USER: ${PHP_USER}
      PHP_SENDMAIL_PATH: ${PHP_SENDMAIL_PATH}
      SMTP_HOSTNAME: ${SMTP_HOSTNAME}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      HOST_USER_ID: ${HOST_USER_ID}
      PHP_CRONTAB: |
        * * * * * php -r "mail('test@example.com','CRON mail', 'Test e-mail from CRON.', 'From: cron@example.com');"
        2 * * * * php -r "mail('test@example.com','CRON mail 2', 'Test 2 e-mail from CRON.', 'From: cron@example.com');"
    command: /usr/sbin/crond -f -d 0
    networks:
      - project_network
    volumes:
#      - html_data:${PROJECT_ROOT}
      - ../codebase:${PROJECT_ROOT}
    deploy:
      replicas: 1

networks:
  frontend_network:
    external: true
  project_network:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_network

volumes:
#  html_data:
#    name: ${COMPOSE_PROJECT_NAME}_html_data
##    driver_opts:
##      type: nfs
##      o: addr=${NFS_HOSTNAME},nolock,soft,rw
##      device: :${NFS_PATH}/${COMPOSE_PROJECT_NAME}/volumes/html_data
  mariadb_data:
    name: ${COMPOSE_PROJECT_NAME}_mariadb_data
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_HOSTNAME},nolock,soft,rw
#      device: :${NFS_PATH}/${COMPOSE_PROJECT_NAME}/volumes/mariadb_data
