version: '3.8'

services:
  mkcert:
    image: vavyskov/mkcert:${MKCERT_VERSION:-1.4.3-alpine3.13}
    container_name: ${COMPOSE_PROJECT_NAME:-traefik}_mkcert
    environment:
      SERVER_HOSTNAMES: ${SERVER_HOSTNAMES:-*.localhost.dev *.localhost.test *.example.com *.example.edu}
      HOST_USER_ID: ${HOST_USER_ID:-1000}
      HOST_USER_NAME: ${HOST_USER_NAME:-user}
    volumes:
      - ./certificates:/root/.local/share/mkcert

networks:
  frontend_network:
    external: true