version: "3"

services:

  traefik:
    image: traefik:2.1
    container_name: traefik
    command:
      ## Traefik will listen on port 8080 by default for API request
      - --api.insecure=true
      ## Enabling docker provider
      - --providers.docker=true
      ## Do not expose containers unless explicitly told so
      - --providers.docker.exposedByDefault=false
      ## Traefik will listen to incoming request on the port 80 (HTTP - custom name)
      - --entrypoints.http.address=:80

      ## Traefik will listen to incoming request on the port 443 (HTTPS - custom name)
      - --entrypoints.https.address=:443
      ## Enable a tls challenge named "mytlschallenge"
      - --certificatesResolvers.mytlschallenge.acme.tlschallenge=true
      - --certificatesResolvers.mytlschallenge.acme.email=postmaster@mydomain.com
      ## Tell to store the certificate on a path under our volume
      - --certificatesResolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json

      ## Test/Debug
      #- --log.level=DEBUG
      #- --certificatesResolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      ## Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      ## Create a letsencrypt dir within the folder where the docker-compose file is
      #- ./letsencrypt:/letsencrypt
    deploy:
      placement:
          constraints: [node.role == manager]
    labels:
        - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
    networks:
      - backend
  
networks:
  backend:
    external:
      name: backend