# Entry Points
entryPoints:
  http:
    address: :80
  https:
    address: :443

# Let’s Encrypt
certificatesResolvers:
  letsEncrypt:
    acme:
      email: you@example.com
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

# Docker configuration backend
providers:
  docker:
    #defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
  
# API and dashboard configuration
api:
  insecure: true