version: '3.5'

services:
  php-fpm:
    image: vavyskov/php:${PHP_VERSION:-7.4-fpm-alpine3.11}
    container_name: ${COMPOSE_PROJECT_NAME:-project}_php-fpm
    #hostname: "web_app_fpm"
    ## Docker Swarm (docker stack deploy) does not support "depends_on" :(
    #depends_on:
    #  - mariadb
    #  - postgres
    environment:
      #FASTCGI_PORT: ${FASTCGI_PORT:-9001}
      PROJECT_MODE: ${PROJECT_MODE:-dev}
      #PHP_HOME: ${PHP_HOME:-/var/www}
      PHP_USER: ${PHP_USER:-user}
      SMTP_HOSTNAME: ${SMTP_HOSTNAME:-192.168.99.100}
      SMTP_PORT: ${SMTP_PORT:-1026}
      #SMTP_FROM: ${SMTP_FROM}
      SMTP_FROM: ${SMTP_FROM:-team@example.com}
      ## SMTP user example: ${SMTP_USER:-user}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-password}
      ## Proxy server example: ${PROXY_SERVER:-http://user:password@proxy.example.com:8080}
#      PROXY_SERVER: ${PROXY_SERVER}
      XDEBUG_HOSTNAME: ${XDEBUG_HOSTNAME:-192.168.99.1}
      #APP_ENV: ${APP_ENV}
      #APP_SECRET: ${APP_SECRET}
      #DATABASE_HOSTNAME: mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@database:3306/${MARIADB_DATABASE}?serverVersion=5.7
    networks:
      - project_network
    volumes:
      - html_data:${PROJECT_ROOT:-/var/www/html}
      #- ~/.ssh:${SSH_HOME:-/var/www}/.shared/.ssh:ro
      #- ~/.gitconfig:${SSH_HOME}/.shared/.gitconfig:ro
    #working_dir: /var/www/html
    deploy:
      replicas: 1

networks:
  project_network:
    external: true

volumes:
  html_data:
    name: ${COMPOSE_PROJECT_NAME:-project}_html_data
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_HOSTNAME:-nfs.example.com},nolock,soft,rw
#      device: :${NFS_PATH:-/media/nfs_docker/dev/project/volumes/html_data}
