version: '3.5'

services:

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION:-4}
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      SCRIPT_NAME: /pgadmin
      #PGADMIN_ENABLE_TLS: True
      #PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: True
      #PGADMIN_CONFIG_LOGIN_BANNER: "Authorised users only!"
      #PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    volumes:
       - pgadmin_data:/var/lib/pgadmin
       #- pgadmin:/root/.pgadmin
       #- /private/var/lib/pgadmin:/var/lib/pgadmin
       #- /path/to/certificate.cert:/certs/server.cert
       #- /path/to/certificate.key:/certs/server.key
       #- /tmp/servers.json:/pgadmin4/servers.json
    ports:
      - target: 80
        published: ${PGADMIN_PORT:-5050}
    networks:
      - backend_network
      - frontend_network
    restart: unless-stopped
    #restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
      - traefik.http.routers.pgadmin.service=pgadmin
      - traefik.http.routers.pgadmin.rule=Host(`example.com`) # && Path(`/pgadmin`) ## viz SCRIPT_NAME environment
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.entrypoints=https

networks:
  backend_network:
    external: true
  frontend_network:
    external: true

volumes:
  pgadmin_data:
    #driver_opts:
    #  type: nfs
    #  o: addr=${NFS_HOSTNAME:-nfs.example.com},nolock,soft,rw
    #  device: :${NFS_PATH:-/media/nfs_docker/dev/pgadmin/volumes/pgadmin_data}