version: '3'

services:

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION:-4}
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      SCRIPT_NAME: /pgadmin
      #PGADMIN_ENABLE_TLS: True
      #PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: True
      #PGADMIN_CONFIG_LOGIN_BANNER: "Authorised users only!"
      #PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    volumes:
       - pgadmin:/var/lib/pgadmin
       #- pgadmin:/root/.pgadmin
       #- /private/var/lib/pgadmin:/var/lib/pgadmin
       #- /path/to/certificate.cert:/certs/server.cert
       #- /path/to/certificate.key:/certs/server.key
       #- /tmp/servers.json:/pgadmin4/servers.json
    ports:
      - ${PGADMIN_PORT:-5050}:80
    networks:
      - frontend
    restart: unless-stopped
    #restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true

      #- traefik.http.routers.pgadmin.rule=Host(`pgadmin.example.com`)
      - traefik.http.routers.pgadmin.rule=Host(`example.com`)
      #- traefik.http.routers.pgadmin.rule=Host(`example.com`) && Path(`/pgadmin`)

      - traefik.http.services.pgadmin.loadbalancer.server.port=80

networks:
  frontend:
    external: true

volumes:
    pgadmin: