tls:
#  certificates:
#    - certFile: "/etc/ssl/path/project-1.crt"
#      keyFile: "/etc/ssl/path/project-1.key"
#    - certFile: "/etc/ssl/path/project-2.crt"
#      keyFile: "/etc/ssl/path/project-2.key"
#    - certFile: "/etc/ssl/path/project-3.crt"
#      keyFile: "/etc/ssl/path/project-3.key"
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/ssl/certificates/server.crt"
        keyFile: "/etc/ssl/certificates/server.key"

#http:
#  routers:
#    traefik:
#      rule: "Host(`traefik.example.com`)"
#      service: "api@internal"
#      tls:
#        domains:
#          - main: "localhost.dev"
#            sans:
#              - "*.localhost.dev"
#          - main: "localhost.test"
#            sans:
#              - "*.localhost.test"
#          - main: "example.com"
#            sans:
#              - "*.example.com"
#  middlewares:
#    https-redirect:
#      redirectScheme:
#        scheme: https