version: '3.5'

services:
  php-fpm:
    image: vavyskov/php:7.4-fpm-alpine3.11
    container_name: project_php-fpm
    #hostname: "web_app_fpm"
    ## Docker Swarm (docker stack deploy) does not support "depends_on" :(
    #depends_on:
    #  - mariadb
    #  - postgres
    environment:
      #FASTCGI_PORT: 
      PROJECT_MODE: dev
      #TIME_ZONE: UTC
      #PHP_HOME: 
      PHP_USER: user
      SMTP_HOSTNAME: 192.168.99.107
      SMTP_PORT: 1026
      SMTP_FROM: team@example.com
      SMTP_USER: 
      SMTP_PASSWORD: password
#      PROXY_SERVER: 
      XDEBUG_HOSTNAME: 192.168.99.1
      #APP_ENV: 
      #APP_SECRET: 
      #DATABASE_HOSTNAME: mysql://mariadb:mariadb@database:3306/mariadb?serverVersion=5.7
    networks:
      - project_network
    volumes:
      - html_data:/var/www/html
      #- ~/.ssh:/var/www/.shared/.ssh:ro
      #- ~/.gitconfig:/var/www/.shared/.gitconfig:ro
    #working_dir: /var/www/html
    deploy:
      replicas: 1

networks:
  project_network:
    external: true

volumes:
  html_data:
    name: project_html_data
#    driver_opts:
#      type: nfs
#      o: addr=nfs.example.com,nolock,soft,rw
#      device: :/media/nfs_docker/dev/project/volumes/html_data

