## export CONSUL_REPLICAS=$(docker node ls -q | wc -l)
##
## docker network create --driver=overlay frontend_network
## docker stack deploy -c docker-compose.yml consul
##
## unset CONSUL_REPLICAS

version: '3.5'

services:
  leader:
    image: consul:${CONSUL_VERSION:-1.7}
    container_name: ${COMPOSE_PROJECT_NAME:-consul}_leader
    #hostname: "{{.Node.Hostname}}"
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    #command: [ "agent", "-server", "-bootstrap-expect=3", "-retry-max=3", "-retry-interval=10s", "-datacenter=prd", "-join=consul-cluster", "-retry-join=consul-cluster", "-bind={{ GetInterfaceIP \"eth0\" }}", "-client=0.0.0.0", "-ui"]
    volumes:
      - leader_data:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      #- CONSUL_BIND_INTERFACE=eth1
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    ports:
      - target: 8500
        published: 8500
    networks:
      - frontend_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME:-consul}_consul-leader.loadbalancer.server.port=8500
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-consul}_consul-leader.rule=Host(`consul.example.com`)
      ## BasicAuth (BCrypt or MD5 not SHA1) - https://www.htaccesstools.com/htpasswd-generator/
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-consul}_consul-leader.middlewares=${COMPOSE_PROJECT_NAME:-consul}_auth-users
      ## In password type $ as $$
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME:-consul}_auth-users.basicauth.users=consul:$$2y$$10$$LquX.DzAE0BtD2WpNqoaRe8LaqY4I42vLOKCjEAIA46yScZXaVs4.
  replica:
    image: consul:${CONSUL_VERSION:-1.7}
    container_name: ${COMPOSE_PROJECT_NAME:-consul}_replica
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - replica_data:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      #- CONSUL_BIND_INTERFACE=eth1
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - frontend_network
    deploy:
      mode: replicated
      ## replicas 0 ~ one node (consul-leader only), max 5
      ## Current number of nodes: $(docker node ls -q | wc -l)
      replicas: ${CONSUL_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id

networks:
  frontend_network:
    external: true

volumes:
  leader_data:
    name: consul_leader_data
#    driver_opts:
#      type: nfs
#      o: addr=nfs.example.com,nolock,soft,rw
#      device: :/media/nfs_docker/dev/consul/volumes/consul_leader_data
  replica_data:
    name: consul_replica_data
#    driver_opts:
#      type: nfs
#      o: addr=nfs.example.com,nolock,soft,rw
#      device: :/media/nfs_docker/dev/consul/volumes/consul_replica_data
