version: '3.5'

services:

  adminer:
    image: adminer:${ADMINER_VERSION:-4}
    container_name: ${COMPOSE_PROJECT_NAME:-adminer}_adminer
    ports:
      - target: 8080
        published: ${ADMINER_PORT:-8081}
    networks:
      - frontend_network
      - adminer_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME:-adminer}_adminer.loadbalancer.server.port=8080
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-adminer}_adminer.rule=Host(`example.com`) && Path(`/adminer`)
#      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-adminer}_adminer.tls=true

networks:
  frontend_network:
    external: true
  adminer_network:
    external: true