version: '3.5'

services:

  adminer:
    image: adminer:${ADMINER_VERSION:-4}
    container_name: adminer
    ports:
      - target: 8080
        published: ${ADMINER_PORT:-8081}
    networks:
      - backend_network
      - frontend_network
    deploy:
      replicas: 1
      placement:
          constraints:
            - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.adminer.loadbalancer.server.port=8080
      - traefik.http.routers.adminer.service=adminer
      - traefik.http.routers.adminer.rule=Host(`example.com`) && Path(`/adminer`)
      - traefik.http.routers.adminer.tls=true
      - traefik.http.routers.adminer.entrypoints=https

networks:
  backend_network:
    external: true
  frontend_network:
    external: true