## docker network create --driver=overlay backend_network;
## docker network create --driver=overlay frontend_network;
## docker stack deploy --compose-file=docker-compose.yml stack-lepp

version: '3.5'

services:
  nginx:
    image: vavyskov/nginx:1.17-php-fpm-alpine3.10
    container_name: stack-lepp_nginx
    volumes:
      - html_data:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - backend_network
      - frontend_network
    deploy:
      replicas: 1
    labels:
      - traefik.enable=true
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - traefik.http.routers.nginx.service=nginx
      - traefik.http.routers.nginx.rule=Host(`stack-lepp.example.com`)
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.entrypoints=https

  php-fpm:
    image: vavyskov/php:7.4-fpm-alpine3.11
    container_name: stack-lepp_php-fpm
    environment:
      PROJECT_MODE: dev
      PHP_USER: devstacklepp
      SMTP_HOSTNAME: 192.168.99.100
      SMTP_PORT: 1026
      SMTP_FROM: team@example.com
      SMTP_USER: team
      SMTP_PASSWORD: password
    networks:
      - backend_network
    volumes:
      - html_data:/var/www/html
    deploy:
      replicas: 1

  ssh:
    image: vavyskov/ssh:php7.4-cli-alpine3.11
    container_name: stack-lepp_ssh
    depends_on:
      - php-fpm
    environment:
      PROJECT_MODE: dev
      SSH_USER: devstacklepp
      SSH_PASSWORD: devstacklepp
      GIT_EMAIL: my@email.com
      GIT_NAME: My Name
      PROXY_SERVER: http://user:password@proxy.example.com:8080
      XDEBUG_HOSTNAME: 192.168.99.100
    ports:
      - target: 22
        published: 2222
    networks:
      - backend_network
    volumes:
      - html_data:/var/www/html:nocopy
#      - ~/.ssh:/var/www/.shared/.ssh:ro
#      - ~/.gitconfig:/var/www/.shared/.gitconfig:ro
    deploy:
      replicas: 1

  postgres:
    image: postgres:12.2-alpine
    container_name: stack-lepp_postgres
    environment:
      POSTGRES_USER: devstacklepp
      POSTGRES_PASSWORD: devstacklepp
      POSTGRES_DB: devstacklepp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5434
    networks:
      - backend_network
    deploy:
      replicas: 1

networks:
  backend_network:
    external: true
  frontend_network:
    external: true

volumes:
  html_data:
    #driver_opts:
    #  type: nfs
    #  o: addr=${NFS_HOSTNAME:-nfs.example.com},nolock,soft,rw
    #  device: :${NFS_PATH:-/media/nfs_docker/dev/stack-lepp/volumes/html_data}
  postgres_data:
    #driver_opts:
    #  type: nfs
    #  o: addr=${NFS_HOSTNAME:-nfs.example.com},nolock,soft,rw
    #  device: :${NFS_PATH:-/media/nfs_docker/dev/stack-lepp/volumes/postgres_data}
