version: '3.2'

services:

  agent:
    image: portainer/agent:${AGENT_VERSION:-1.5.1}
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent_network
    deploy:
      mode: global
      placement:
        constraints: 
          - node.platform.os == linux

  portainer:
    image: portainer/portainer:${PORTAINER_VERSION:-1.23.0}
    container_name: portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    ports:
      - ${PORTAINER_PORT:-9002}:9000
      - 8000:8000
    networks:
      - portainer_agent_network
      - frontend_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.service=portainer

      - traefik.http.routers.portainer.rule=Host(`portainer.example.com`)
      #- traefik.fronted.rule=PathPrefix:/portainer
      #- traefik.http.routers.portainer.rule=Host(`portainer.example.com`) && Path(`/portainer`)

networks:
  portainer_agent_network:
    driver: overlay
    attachable: true
  frontend_network:
    external: true

volumes:
  portainer_data:
