version: "3.5"

services:
  chromium:
    image: zenika/alpine-chrome:81-with-puppeteer
    container_name: chromium_chromium
    command:
      - chromium-browser
      - --headless
      - --disable-gpu
      - --no-sandbox
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
    ports:
      - target: 9222
        published: 9222
    networks:
      - frontend_network
    deploy:
      replicas: 1

networks:
  frontend_network:
    external: true
