version: "3.5"

services:
  chromium:
    image: zenika/alpine-chrome:81-with-puppeteer
    container_name: chromium_chromium
    command:
      - chromium-browser
      - --headless
      - --disable-gpu
      - --no-sandbox
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
    ports:
      - target: 9222
        published: 9222
    networks:
      - frontend_network
#      - chromium_network
#    volumes:
#      - tmp_data:/tmp:ro,nocopy
    deploy:
      replicas: 1

networks:
  frontend_network:
    external: true
#  chromium_network:
#    external: true

#volumes:
#  tmp_data:
#    name: chromium_tmp_data
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_HOSTNAME:-nfs.example.com},nolock,soft,ro
#      device: :${NFS_PATH:-/media/nfs_docker/dev/chromium/volumes/tmp_data}
