version: "3.7"

services:
  php:
#    image: wodby/php-dev:$PHP_TAG
    image: wodby/php:${PHP_TAG}
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S $SMTP_HOSTNAME:$SMTP_PORT

      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby

#      COLUMNS: 80 # Set 80 columns for docker exec -it.
#      # Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_MODE: debug
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_IDEKEY: "my-ide"
#      PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
#      PHP_XDEBUG_CLIENT_HOST: host.docker.internal # Docker 18.03+ Mac/Win
#      PHP_XDEBUG_CLIENT_HOST: 10.0.75.1 # Windows, Docker < 18.03
#      PHP_XDEBUG_LOG: /tmp/php-xdebug.log
#      # PHPUnit Drupal testing configurations
#      SIMPLETEST_BASE_URL: "http://nginx"
#      SIMPLETEST_DB: "${MARIADB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${MARIADB_HOST}/${DB_NAME}#tests_"
#      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'

      SSH_AUTH_SOCK: /ssh-agent
    volumes:
#      - ./:${PROJECT_ROOT}:cached # Dev
      - codebase:${PROJECT_ROOT} # Prod
      - $SSH_AUTH_SOCK:/ssh-agent:ro # Forward local machine SSH key to docker (ssh-forwarding on macOS hosts - instead of mounting the path of $SSH_AUTH_SOCK, you have to mount this path - /run/host-services/ssh-auth.sock)
## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/drupal/local#docker-for-mac
#      - mutagen:${PROJECT_ROOT}
## For XHProf and Xdebug profiler traces
#      - files:/mnt/files
    networks:
      - backend_network

networks:
  backend_network:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_network

volumes:
## For production
  codebase:
## For Xdebug profiler
#  files:
