version: "3.8"

services:
  mkcert:
    image: vavyskov/mkcert:${MKCERT_VERSION:-1.4.3-1.1.0}
    container_name: ${COMPOSE_PROJECT_NAME:-mkcert}_mkcert
    environment:
      MKCERT_HOSTNAMES: "*.localhost.dev *.localhost.test *.example.com *.example.edu"
      HOST_USER_ID: 1000
      HOST_USER_NAME: user
    volumes:
      - ./certificates:/root/.local/share/mkcert
    network_mode: none
