version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION:-latest}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      #POSTGRES_DB: ${POSTGRES_DATABASE:-project}
      #PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
       #- postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - backend
    restart: unless-stopped
    #restart: always

networks:
  backend:

volumes:
    postgres:
