version: '3.5'

services:

  postgres:
    image: postgres:${POSTGRES_VERSION:-12}
    container_name: ${COMPOSE_PROJECT_NAME:-postgres}_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      #POSTGRES_DB: ${POSTGRES_DATABASE:-project}
      #PGDATA: /data/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
       #- postgres:/data/postgres
    ports:
      - target: 5432
        published: ${POSTGRES_PORT:-5432}
    networks:
      - postgres_network
    restart: unless-stopped
    #restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  postgres_network:
    external: true

volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME:-postgres}_postgres_data
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_HOSTNAME:-nfs.example.com},nolock,soft,rw
#      device: :${NFS_PATH:-/media/nfs_docker/dev/postgres/volumes/postgres_data}