version: '3'

services:

  postgres:
    image: postgres:${POSTGRES_VERSION:-12}
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      #POSTGRES_DB: ${POSTGRES_DATABASE:-project}
      #PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
       #- postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - network_gateway
    restart: unless-stopped
    #restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  network_gateway:
    external: true
      #name: network_gateway

volumes:
    postgres:
