version: '3.5'

services:

  visualizer:
    image: dockersamples/visualizer:${VISUALIZER_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME:-visualizer}_visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 8080
        published: ${VISUALIZER_PORT:-9003}
    networks:
      - frontend_network
    deploy:
      replicas: 1
      placement:
          constraints:
            - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME:-visualizer}_visualizer.loadbalancer.server.port=8080
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-visualizer}_visualizer.rule=Host(`visualizer.example.com`)
      #- traefik.http.routers.${COMPOSE_PROJECT_NAME:-visualizer}_visualizer.rule=Host(`visualizer.example.com`) && Path(`/visualizer`)
      #- traefik.http.routers.${COMPOSE_PROJECT_NAME:-visualizer}_visualizer.rule=Host(`visualizer.example.com`) && PathPrefix(`/visualizer`)
#      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-visualizer}_visualizer.tls=true

      ## BasicAuth (BCrypt or MD5 not SHA1) - https://www.htaccesstools.com/htpasswd-generator/
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-visualizer}_visualizer.middlewares=${COMPOSE_PROJECT_NAME:-visualizer}_auth-users
      ## In password type $ as $$
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME:-visualizer}_auth-users.basicauth.users=visualizer:$$2y$$10$$uLQiFnpnlXso2it40SpzgOkvBsSEu34qMD6X1hvFVHB6qZgbfRRQu

networks:
  frontend_network:
    external: true