# https://github.com/SeleniumHQ/docker-selenium
#
# To start Docker in Swarm mode, you need to run `docker swarm init`
# To deploy the Grid, `docker stack deploy -c docker-compose.yml grid`
# Stop with `docker stack rm grid`
# Stop swarm mode `docker swarm leave --force`

version: '3.7'

services:
  hub:
    image: selenium/hub:4.1.4-20220427
    hostname: selenium
    ports:
      - target: 4444
        published: 4444
      - target: 4443
        published: 4443
      - target: 4442
        published: 4442
    networks:
      - frontend_network
#    deploy:
#        replicas: 1

  chrome:
    image: selenium/node-chrome:4.1.4-20220427
    shm_size: 2gb
#    volumes:
#        - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
    networks:
      - frontend_network
    deploy:
      replicas: 1

  firefox:
    image: selenium/node-firefox:4.1.4-20220427
    shm_size: 2gb
#    volumes:
#        - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
    networks:
      - frontend_network
    deploy:
      replicas: 1

  edge:
    image: selenium/node-edge:4.1.4-20220427
    shm_size: 2gb
#    volumes:
#        - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
    networks:
      - frontend_network
    deploy:
      replicas: 1

networks:
  frontend_network:
    external: true
