# To start Docker in Swarm mode, you need to run `docker swarm init`
# To deploy the Grid, `docker stack deploy -c docker-compose.yml grid`
# Stop with `docker stack rm grid`

version: '3.5'

services:
  hub:
    image: selenium/hub:3.141.59-zinc
    hostname: selenium
    ports:
      - target: 4444
        published: 4444
    networks:
      - frontend_network
    deploy:
      replicas: 1

  chrome:
    image: selenium/node-chrome:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    networks:
      - frontend_network
    deploy:
      replicas: 1

  firefox:
    image: selenium/node-firefox:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    networks:
      - frontend_network
    deploy:
      replicas: 1

networks:
  frontend_network:
    external: true
